language: python

python:
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install coverage
  - pip install coveralls

script:
  - python -m black .
  - coverage run manage.py test bikingapp

after_success: coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-west-2"
  app: "bikingapp-master"
  env: "bikingapp-master-env"
  bucket_name: "elasticbeanstalk-us-west-2-434236253957"
  on:
    repo: gcivil-nyu-org/INET-Team-3-F2022
    branch: master
