language: python
python:  
  - "3.8"
install:
  - pip install -r bikerapp/requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls
before_script:
  - python manage.py migrate
script:
  - python -m black . --check
  - python bikerapp/manage.py test bikingapp